[project]
name = "mathpy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "matplotlib-venn>=1.1.2",
    "pyqt6>=6.9.0",
    "sympy>=1.14.0",
]
